#if !defined(CONSTANTS_H)
#define CONSTANTS_H

#define FIELD_SIZE 8
#define FIELD_WIDTH 500
#define FIELD_HEIGHT 500

#define FIELD_BORDER_THICKNESS 1

#define FIELD_CELL_HEIGHT \
    ((float)(FIELD_HEIGHT - FIELD_BORDER_THICKNESS * (FIELD_SIZE)) / FIELD_SIZE)
#define FIELD_CELL_WIDTH \
    ((float)(FIELD_WIDTH - FIELD_BORDER_THICKNESS * (FIELD_SIZE)) / FIELD_SIZE)

#define BLOCK_CELL_HEIGHT FIELD_CELL_HEIGHT
#define BLOCK_CELL_WIDTH FIELD_CELL_WIDTH
#define BLOCK_CELL_BORDER_THICKNESS (6)

#define EMPTY_CELL_COLOR ColorBrightness(LIGHTGRAY, -0.225f)
#define FIELD_BORDER_COLOR DARKGRAY

#endif // CONSTANTS_H
